openapi: 3.2.0
info:
  title: NMM Distributor Invoices API
  description: Distributor APIs to register, cancel, suspend NMM Installs and retrieve usage information. Contact nmm.support@getnerdio.com to request APIKey and access to Mothership portal.
  version: v1
tags:
- name: Invoices
paths:
  /api-v{version}/invoices:
    get:
      tags:
      - Invoices
      summary: Collect consumption information. This API is typically used for monthly billing.
      parameters:
      - name: PeriodStart
        in: query
        description: Start Date (first day of month in mm/dd/yyyy format)
        schema:
          type: string
          format: date-time
      - name: PeriodEnd
        in: query
        description: End Date (last day of month in mm/dd/yyyy format)
        schema:
          type: string
          format: date-time
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
  /api-v{version}/invoices/grouped:
    get:
      tags:
      - Invoices
      summary: Collect consumption information grouped by partner and account. This API is typically used for monthly billing.
      parameters:
      - name: PeriodStart
        in: query
        description: Start Date (first day of month in mm/dd/yyyy format)
        schema:
          type: string
          format: date-time
      - name: PeriodEnd
        in: query
        description: End Date (last day of month in mm/dd/yyyy format)
        schema:
          type: string
          format: date-time
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
