openapi: 3.2.0
info:
  title: NMM Distributor Install API
  description: Distributor APIs to register, cancel, suspend NMM Installs and retrieve usage information. Contact nmm.support@getnerdio.com to request APIKey and access to Mothership portal.
  version: v1
tags:
- name: Install
paths:
  /api-v{version}/installs:
    get:
      tags:
      - Install
      summary: Retrieve a list of all NMM installs you have registered via API or Mothership
      parameters:
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
      operationId: getApiV{version}Installs
      x-operation-id-source: derived
  /api-v{version}/register:
    post:
      tags:
      - Install
      summary: Claim a MSP partner's existing and future NMM installs in their Azure…
      parameters:
      - name: SubscriptionID
        in: query
        description: Azure Subscription ID
        required: true
        schema:
          type: string
      - name: SendConfirmationEmail
        in: query
        description: Notify partner their NMM install has been assigned to distributor
        schema:
          type: boolean
      - name: ConnectAssetId
        in: query
        description: Connect Asset ID
        schema:
          type: string
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
      operationId: postApiV{version}Register
      x-operation-id-source: derived
  /api-v{version}/suspend:
    put:
      tags:
      - Install
      summary: Suspend all installs in an Azure subscription.
      parameters:
      - name: SubscriptionID
        in: query
        description: Azure Subscription ID
        required: true
        schema:
          type: string
      - name: SendConfirmationEmail
        in: query
        description: Notify partner their NMM install has been assigned to distributor
        schema:
          type: boolean
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
      operationId: putApiV{version}Suspend
      x-operation-id-source: derived
  /api-v{version}/reactivate:
    put:
      tags:
      - Install
      summary: Unsuspend all installs in an Azure subscription.
      parameters:
      - name: SubscriptionID
        in: query
        description: Azure Subscription ID
        required: true
        schema:
          type: string
      - name: SendConfirmationEmail
        in: query
        description: Notify partner their NMM install has been assigned to distributor
        schema:
          type: boolean
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
      operationId: putApiV{version}Reactivate
      x-operation-id-source: derived
  /api-v{version}/cancel:
    delete:
      tags:
      - Install
      summary: Unregister previously claimed partner NMM installs and suspend those installs.
      parameters:
      - name: SubscriptionID
        in: query
        description: Azure Subscription ID
        required: true
        schema:
          type: string
      - name: SendConfirmationEmail
        in: query
        description: Notify partner their NMM install is suspended and no longer registered with distributor.
        schema:
          type: boolean
      - name: version
        in: path
        description: API Version
        required: true
        schema:
          type: string
      - name: APIKey
        in: header
        description: API key for authentication
        required: true
      responses:
        '200':
          description: Ok. API call executed successfully.
        '400':
          description: Bad request. Invalid parameters or invalid parameter.
        '401':
          description: Unauthorized. APIKey doesnot authorize you to retrieve the information requested.
        '422':
          description: Unprocessable entity. Azure subscription ID you specified is not valid or may not be a GUID.
        '500':
          description: Internal server error. The information supplied in the parameters is incorrect.
        '409':
          description: Conflict. Another distributor has already registered NMM Installs by partner you are trying to register.
      operationId: deleteApiV{version}Cancel
      x-operation-id-source: derived
